// VSCode Dark Modern 主题定义
export function defineDarkModernTheme(monaco) {
  monaco.editor.defineTheme('dark-modern', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6a9955', fontStyle: 'italic' },
      { token: 'keyword', foreground: '569cd6' },
      { token: 'string', foreground: 'ce9178' },
      { token: 'number', foreground: 'b5cea8' },
      { token: 'type', foreground: '4ec9b0' },
      { token: 'class', foreground: '4ec9b0' },
      { token: 'function', foreground: 'dcdcaa' },
      { token: 'variable', foreground: '9cdcfe' },
      { token: 'operator', foreground: 'd4d4d4' },
      { token: 'delimiter', foreground: 'd4d4d4' },
      { token: 'tag', foreground: '569cd6' },
      { token: 'attribute.name', foreground: '9cdcfe' },
      { token: 'attribute.value', foreground: 'ce9178' },
      // Python 专用 token
      { token: 'keyword.control.python', foreground: 'c586c0' },
      { token: 'keyword.operator.python', foreground: 'd4d4d4' },
      { token: 'string.python', foreground: 'ce9178' },
      { token: 'comment.line', foreground: '6a9955', fontStyle: 'italic' },
      { token: 'decorator', foreground: 'd7ba7d' },
      { token: 'self', foreground: '569cd6' },
    ],
    colors: {
      'editor.background': '#1e1e1e',
      'editor.foreground': '#cccccc',
      'editor.lineHighlightBackground': '#2a2d2e',
      'editor.lineHighlightBorder': '#2a2d2e',
      'editorLineNumber.foreground': '#6e7681',
      'editorLineNumber.activeForeground': '#c6c6c6',
      'editor.selectionBackground': '#264f78',
      'editor.inactiveSelectionBackground': '#3a3d41',
      'editor.selectionHighlightBackground': 'add6ff2e',
      'editorCursor.foreground': '#aeafad',
      'editorWhitespace.foreground': '3b3b3b',
      'editorIndentGuide.background1': '#404040',
      'editorIndentGuide.activeBackground1': '#707070',
      'editorGutter.background': '#1e1e1e',
      'editorWidget.background': '#252526',
      'editorWidget.border': '#454545',
      'editorSuggestWidget.background': '#252526',
      'editorSuggestWidget.border': '#454545',
      'editorSuggestWidget.foreground': '#cccccc',
      'editorSuggestWidget.selectedBackground': '#094771',
      'editorHoverWidget.background': '#252526',
      'editorHoverWidget.border': '#454545',
      'editorError.foreground': '#f48771',
      'editorWarning.foreground': '#cca700',
      'editorBracketMatch.background': '#0064001a',
      'editorBracketMatch.border': '#888888',
      'scrollbarSlider.background': '79797966',
      'scrollbarSlider.hoverBackground': '646464b3',
      'scrollbarSlider.activeBackground': 'bfbfbf66',
      'input.background': '#3c3c3c',
      'input.foreground': '#cccccc',
      'input.border': '#3c3c3c',
      'focusBorder': '#007fd4',
      'list.activeSelectionBackground': '#094771',
      'list.activeSelectionForeground': '#ffffff',
      'list.hoverBackground': '#2a2d2e',
      'list.inactiveSelectionBackground': '#37373d',
    },
  });
}
